development:
  host: localhost
  database: caravan_development
  adapter: postgres

test:
  host: localhost
  database: caravan_test
  adapter: postgres

production:
  database: caravan
  adapter: postgres
