development:
  host: localhost
  database: caravan_development
  adapter: postgresql

test:
  host: localhost
  database: caravan_test
  adapter: postgresql

production:
  database: caravan
  adapter: postgresql
